[General]
cmdenv-express-mode = true
cmdenv-autoflush = true
cmdenv-status-frequency = 1s
**.cmdenv-log-level = info



image-path = ../../images
network = ned.V2X


##########################################################
#            Simulation parameters                       #
##########################################################
debug-on-errors = true
print-undisposed = true

sim-time-limit =200s
**.scalar-recording = true
**.vector-recording = true
*.playgroundSizeX = 2500m
*.playgroundSizeY = 2500m
*.playgroundSizeZ = 50m

##########################################################
# Annotation parameters                                  #
##########################################################
*.annotations.draw = true
##########################################################
#            TraCIScenarioManager parameters             #
##########################################################
*.manager.updateInterval = 0.01s
#make 0.01s for actual results
*.manager.host = "localhost"
*.manager.port = 9999
*.manager.autoShutdown = true
*.manager.moduleType= "ned.Vehicle"
#*.manager.moduleName="node" 

*.manager.configFile = "simulations/ratnapark/run.sumocfg"
#replace the name pulchowk with ratnapark based on the scenario
*.socketInterface.port=9998
*.socketInterface.useTcp=true 
#Uses TCP sockets if true and UDP sockets if false. TCP is more reliable but may introduce more overhead, while UDP is faster but less reliable. Choose based on your simulation requirements.
*.timeSynchronizer.stepSize = 0.1
#make 0.1 for final simulation
############## Metrics Collector Settings ##################################
*.metricsCollector.collectionInterval = 1s
*.metricsCollector.nfv_infra = "metrics/nfv_infrastructure.csv"
*.metricsCollector.nfv_service = "metrics/nfv_service_flows.csv"
*.metricsCollector.traffic = "metrics/traffic_context.csv"
*.metricsCollector.socket_sent = "metrics/socket_throughput_sent.csv"
*.metricsCollector.socket_recv = "metrics/socket_throughput_recv.csv"
########   CentralRSUManager Settings ####################
*.rsuManager.updateInterval=2s 
*.rsuManager.rsuCoverage=210
*.rsuManager.rsuSpacing=200
*.rsuManager.minSpacingFromJunctionRsus=80
*.rsuManager.deploymentThreshold=3
*.rsuManager.removalThreshold=1
*.rsuManager.hysteresisTime=30s
*.rsuManager.rsuModuleType="ned.RSU"
*.rsuManager.enableDynamicRsu=true


#number of vehicles to be initialized before sending initial message to ns-3
##########################################################
#                       RSU SETTINGS                     #
#                                                        #
#                                                        #
##########################################################

*.rsu*.mobility.x =0
*.rsu*.mobility.y = 0
*.rsu*.mobility.z = 3
*.rsu*.applType = "RsuApp"

###################Connection Manager Settings ########################
#Setting just because the connectionManager in veins does not have default values no use for our case
*.connectionManager.sendDirect = true
*.connectionManager.maxInterfDist = 200m

##########################################################
#                      App Layer                         #
##########################################################
*.node[*].applType = "VehicleApp"
*.node[*].appl.enablePreemption = true
*.node[*].appl.ttlPreemptionDistance=100 ##Distance between vehicle and traffic_light to give preemption signal for emergency vehicle
##########################################################
#                      Mobility                          #
##########################################################
*.node[*].veinsmobility.x = 0
*.node[*].veinsmobility.y = 0
*.node[*].veinsmobility.z = 0
*.node[*].veinsmobility.setHostSpeed = true
*.node[*].veinsmobility.accidentCount = 2
*.node[*].veinsmobility.accidentStart = 3s
*.node[*].veinsmobility.accidentDuration = 30s
*.node[*].veinsmobility.accidentInterval = 20s



